version: "3"

services:
  nginx-test:
    image: nginx:1.19-alpine
    container_name: nginx
    network_mode: "host"
    restart: "unless-stopped"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d/:ro

